select * from sys.dm_exec_sessions
go



SELECT
	SPID,
	VALUE,
	ANSI_SETTING
FROM (SELECT
	@@SPID AS SPID,
	CASE quoted_identifier
		WHEN 1 THEN 'SET'
		ELSE 'OFF'
	END QUOTED_IDENTIFIER,
	CASE arithabort
		WHEN 1 THEN 'SET'
		ELSE 'OFF'
	END ARITHABORT,
	CASE ansi_null_dflt_on
		WHEN 1 THEN 'SET'
		ELSE 'OFF'
	END ANSI_NULL_DFLT_ON,
	CASE ansi_defaults
		WHEN 1 THEN 'SET'
		ELSE 'OFF'
	END ANSI_DEFAULTS,
	CASE ansi_warnings
		WHEN 1 THEN 'SET'
		ELSE 'OFF'
	END ANSI_WARNINGS,
	CASE ansi_padding
		WHEN 1 THEN 'SET'
		ELSE 'OFF'
	END ANSI_PADDING,
	CASE ansi_nulls
		WHEN 1 THEN 'SET'
		ELSE 'OFF'
	END ANSI_NULLS,
	CASE concat_null_yields_null
		WHEN 1 THEN 'SET'
		ELSE 'OFF'
	END CONCAT_NULL_YIELDS_NULL
FROM sys.dm_exec_sessions
WHERE session_id = @@SPID) P
UNPIVOT (VALUE FOR ANSI_SETTING IN (
QUOTED_IDENTIFIER, ARITHABORT, ANSI_NULL_DFLT_ON,
ANSI_DEFAULTS, ANSI_WARNINGS,
ANSI_PADDING, ANSI_NULLS, CONCAT_NULL_YIELDS_NULL
)
) AS unpvt