USE SPACEMAN
GO

SELECT
	cr.ID				AS STORE_ID
	,cr.NAME			AS STORE_NAME
	,conpln.PLN_ID		AS PLN_ID
	,conpln.PLANOGRAM	AS PLN_NAME
FROM
	ACN_PLANOGRAMS conpln
	JOIN SYS_MYS_PLANOCONTAINER syspln ON conpln.PLN_ID = syspln.PLANOID
	RIGHT OUTER JOIN USR_CR_CONTENTRECVRPLANOGRAMS crpln ON syspln.CONTAINERID = crpln.PLANOCONTAINERID
	LEFT OUTER JOIN USR_CR_CONTENTRECVR cr ON crpln.CONTENTRECEIVERID = cr.id
WHERE
	cr.TYPE = N'store'
order BY cr.ID asc