

USE SPACEMAN
GO

SELECT
	a.PLANOID		AS plndb_plnid
	,a.CONTAINERID	AS sysdb_plnid
	,c.id			AS store_id
FROM
	SPACEMAN_SYS.dbo.SYS_MYS_PLANOCONTAINER a
	JOIN ACN_STORE b ON a.PLANOGRAMID = b.PLANOGRAMID
	LEFT JOIN SPACEMAN_SYS.dbo.USR_CR_CONTENTRECVRPLANOGRAMS d ON a.CONTAINERID = d.PLANOCONTAINERID
	LEFT JOIN SPACEMAN_SYS.dbo.USR_CR_STORELIST c ON d.CONTENTRECEIVERID = c.ID