use BENU_SPACEMAN_DAT
GO

ALTER TABLE ACN_STORE
	ADD PLANOGRAMID NVARCHAR(255) NULL
GO

ALTER TABLE ACN_STORE
	ADD PLANOGRAMTEMPLATEID INT NULL
GO

ALTER TABLE ACN_PRODUCT_PLN
	ADD [ACTION] SMALLINT NULL
GO

ALTER TABLE ACN_PRODUCT_PLN
	ADD [TIMESTAMP] FLOAT NULL
GO

ALTER TABLE ACN_PRODUCT_PLN
	ADD LINKPRODUCTID NVARCHAR(255) NULL
GO

