USE SPACEMAN
GO

SELECT
	*
FROM SYS_MYS_VERSION
SELECT
	u.NAME AS uname,
	k.NAME AS prop_name,
	sett.SETTING AS prop_val
FROM SYS_MYS_USERS u
JOIN SYS_MYS_USERSETTINGSSTRING sett
	ON u.USERID = sett.USERID
JOIN SYS_MYS_USERSETTINGKEYS k
	ON k.KEYID = sett.KEYID