SELECT
	a.TABLE_CATALOG
	,a.TABLE_CATALOG
	,b.TABLE_CATALOG
	,a.TABLE_NAME
	,b.TABLE_NAME
	,a.column_name
	,b.column_name
	,a.DATA_TYPE
	,b.DATA_TYPE
FROM
	CONNECTIVITY_DAT.INFORMATION_SCHEMA.COLUMNS a
	FULL OUTER JOIN STOREID.INFORMATION_SCHEMA.COLUMNS b ON a.TABLE_NAME = b.TABLE_NAME
		AND a.COLUMN_NAME = b.COLUMN_NAME
--AND a.DATA_TYPE = b.DATA_TYPE
WHERE
	a.TABLE_CATALOG IS NULL
	OR b.TABLE_CATALOG IS NULL
	OR (a.DATA_TYPE != b.DATA_TYPE)